{'application':{'type':'Application',
          'name':'Template',
    'backgrounds': [
    {'type':'Background',
          'name':'bgExample',
          'title':u'Tutorial GUI',
          'size':(320, 179),
          'statusBar':1,
          'style':['resizeable'],

        'menubar': {'type':'MenuBar',
         'menus': [
             {'type':'Menu',
             'name':'menuFile',
             'label':'&File',
             'items': [
                  {'type':'MenuItem',
                   'name':'menuFileNew',
                   'label':'&New\tCtrl+N',
                  },
                  {'type':'MenuItem',
                   'name':'menuFileOpen',
                   'label':'&Open\tCtrl+O',
                  },
                  {'type':'MenuItem',
                   'name':'menuFileSave',
                   'label':'&Save\tCtrl+S',
                  },
                  {'type':'MenuItem',
                   'name':'menuFileSaveAs',
                   'label':'Save &As...',
                  },
                  {'type':'MenuItem',
                   'name':'fileSep2',
                   'label':'-',
                  },
                  {'type':'MenuItem',
                   'name':'menuFileExit',
                   'label':'E&xit\tAlt+X',
                   'command':'exit',
                  },
              ]
             },
             {'type':'Menu',
             'name':'Edit',
             'label':'&Edit',
             'items': [
                  {'type':'MenuItem',
                   'name':'menuEditUndo',
                   'label':'&Undo\tCtrl+Z',
                  },
                  {'type':'MenuItem',
                   'name':'menuEditRedo',
                   'label':'&Redo\tCtrl+Y',
                  },
                  {'type':'MenuItem',
                   'name':'editSep1',
                   'label':'-',
                  },
                  {'type':'MenuItem',
                   'name':'menuEditCut',
                   'label':'Cu&t\tCtrl+X',
                  },
                  {'type':'MenuItem',
                   'name':'menuEditCopy',
                   'label':'&Copy\tCtrl+C',
                  },
                  {'type':'MenuItem',
                   'name':'menuEditPaste',
                   'label':'&Paste\tCtrl+V',
                  },
                  {'type':'MenuItem',
                   'name':'editSep2',
                   'label':'-',
                  },
              ]
             },
             {'type':'Menu',
             'name':'menuHelp',
             'label':'&Help',
             'items': [
                  {'type':'MenuItem',
                   'name':'menuHelpAbout',
                   'label':'&About ...',
                   'command':'doHelpAbout',
                  },
              ]
             },
         ]
     },
         'components': [

{'type':'Button', 
    'name':'cmdReset', 
    'position':(170, 80), 
    'label':u'Reset', 
    },

{'type':'PasswordField', 
    'name':'txtAuthKey', 
    'position':(90, 36), 
    'size':(216, -1), 
    'backgroundColor':(87, 255, 104, 255), 
    },

{'type':'StaticText', 
    'name':'lblAuthKey', 
    'position':(10, 35), 
    'backgroundColor':(84, 84, 84, 255), 
    'foregroundColor':(107, 255, 134, 255), 
    'text':u'AUTH KEY:', 
    },

{'type':'StaticText', 
    'name':'lblIdent', 
    'position':(10, 10), 
    'backgroundColor':(84, 84, 84, 255), 
    'foregroundColor':(107, 255, 134, 255), 
    'text':u'ID:', 
    },

{'type':'TextField', 
    'name':'txtIdent', 
    'position':(90, 10), 
    'size':(216, -1), 
    'backgroundColor':(67, 255, 100, 255), 
    },

{'type':'Button', 
    'name':'cmdLogin', 
    'position':(60, 80), 
    'label':u'Login', 
    },

] # end components
} # end background
] # end backgrounds
} }
